# Generated by Django 3.2.6 on 2021-09-28 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_event_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pricing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
        ),
    ]
