# Generated by Django 3.2.6 on 2021-09-28 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0005_alter_event_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_remarks',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
