# Generated by Django 3.2.6 on 2021-10-07 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_alter_event_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 7, 11, 56, 44, 72253)),
        ),
    ]
